### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by TekExplorer** [cobwebsh/bepinhecks-installer#1]
A LICENCE is necessary to know what we can do with this software, [What if I don't want a license?](https://choosealicense.com/no-permission/)

I will not be able to legally contribute to this code without it.

Technically speaking, it also means we cannot legally **_use_** this installer as well.

Feel free to use https://choosealicense.com/ to quickly choose one. (Perhaps GNU GPLv3 or MIT?)

**Comment by raineycat** [comment]
Resolved in e297c3a
